default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: <%= ENV['DB_HOST'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>

test:
  <<: *default
  database: ranking_test

production:
  <<: *default
  database: ranking_production
  username: ranking
  password: <%= ENV["RANKING_DATABASE_PASSWORD"] %>
